### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by trsh** [apoterenko/angular2-dynamic-component#21]
This is really slow, when, for example, doing something like this:

```
<tr *ngFor="let row of rows;" class="link" (click)="clickRecord(row)">
        <td dynamic-component *ngFor="let header of headers" [componentContext]="{changedValue: 0}"  [componentTemplate]='"<span></span>"'>

        </td>
      </tr>
```

**Comment by apoterenko** [comment]
How many headers?

**Comment by trsh** [comment]
6 and 40 rows.

**Comment by trsh** [comment]
Maybe that's why angular 2 does not want dynamic components :D

**Comment by apoterenko** [comment]
The Angular2 function compileModuleAndAllComponentsAsync takes too much time, but..
I can implement the inner cache based on dynamic module hash (hash of dynamic function)
=> time should be decreased significantly because:

BEFORE: 
compile time = ROW_COUNT * HEADER_COUNT * time(compileModuleAndAllComponentsAsync)

AFTER:
compile time = HEADER_COUNT * time(compileModuleAndAllComponentsAsync)

**Comment by apoterenko** [comment]
In general, we do not need to recompile each time a module that replicates the functionality...

**Comment by trsh** [comment]
Nice. Give a try! You can label this as F.R.

**Comment by apoterenko** [comment]
Try 1.1.5, should work fine for your case...
But I am not finished yet..

**Comment by trsh** [comment]
@apoterenko tnx. Will check tomorrow.

**Comment by apoterenko** [comment]
Try 1.2.1

See https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts

**Comment by trsh** [comment]
@apoterenko OK. Will let you know. 1.1.5 also works fine for me. Sorry for not responding so long. Was caught up in work.

**Comment by apoterenko** [comment]
See full demo here

https://github.com/apoterenko/angular2-dynamic-component/blob/master/demo/src/app/app.component.ts
